# Generated by Django 5.1.4 on 2025-01-10 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=100, verbose_name='Nome do Produto'),
                ),
                (
                    'sku',
                    models.CharField(
                        max_length=20, unique=True, verbose_name='Código SKU'
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name='Preço'
                    ),
                ),
                (
                    'is_available',
                    models.BooleanField(default=True, verbose_name='Disponível'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'weight',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name='Peso (kg)',
                    ),
                ),
                (
                    'dimensions',
                    models.CharField(
                        blank=True, max_length=50, verbose_name='Dimensões (LxAxP)'
                    ),
                ),
                (
                    'material',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Material'
                    ),
                ),
                (
                    'warranty',
                    models.CharField(
                        blank=True, max_length=50, verbose_name='Garantia'
                    ),
                ),
                (
                    'additional_info',
                    models.TextField(blank=True, verbose_name='Informações Adicionais'),
                ),
                (
                    'product',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='specification',
                        to='products.product',
                        verbose_name='Produto',
                    ),
                ),
            ],
        ),
    ]
