# Generated by Django 5.1.5 on 2025-01-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'products',
            '0003_alter_category_options_alter_productdetail_category_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='category',
                to='products.category',
                verbose_name='Categoria',
            ),
        ),
    ]
